name: Update Readme
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changed_files:
    name: Changed Files
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    steps:
      - name: Test
        run: |
          echo "Running test on branch $(git branch --show-current)"
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changed Files
        uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          matrix: true
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
          files_ignore: |
            create_readme.py

  test_output:
    name: print output
    needs: changed_files
    runs-on: ubuntu-latest
    steps:
      - name: print changed files name
        run: |
          echo ${{ needs.changed_files.outputs.changed-files }}
  update_readme:
    name: Update Readme
    needs: changed_files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJSON(needs.changed_files.outputs.changed-files) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run script and update readme
        run: python create_readme.py ${{ matrix.dir }}
      - name: Commit and Push Changes
        if: github.ref == 'refs/heads/main'
        run: |
          cd ${{ matrix.dir }}
          git status
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add .
          git commit -m "Updated readme on `date` with GitHub Actions" || true
          git pull --ff
          git push origin main || true
